#!/bin/bash

# Import MOS functions
. /usr/local/lib/functions/mos-common

# Make sure the messagebus user/group exists
ensure_users() {
  if ! getent group messagebus >/dev/null 2>&1 ; then
    groupadd --system messagebus >/dev/null 2>&1 || addgroup --system messagebus >/dev/null 2>&1
  fi
  if ! getent passwd messagebus >/dev/null 2>&1 ; then
    useradd --system --gid messagebus --home-dir /nonexistent --shell /usr/sbin/nologin messagebus >/dev/null 2>&1 || \
      adduser --system --no-create-home --ingroup messagebus --home /nonexistent --shell /usr/sbin/nologin messagebus >/dev/null 2>&1
  fi
}

pre_install() {
  # Ensure users
  ensure_users
}

install() {
  # Start dbus and bluez
  /usr/bin/plugins/bluez start >/dev/null 2>&1
}

mos_start() {
  # Ensure users
  ensure_users

  # Start dbus and bluez
  /usr/bin/plugins/bluez start >/dev/null 2>&1
}
